config/routes.rb
Contacts::Application.routes.draw do
  resources :contacts

  root to: 'static_pages#home'

  match '/help',                to: 'static_pages#help'
  match '/about',               to: 'static_pages#about'
  match '/contact_information', to: 'static_pages#contact_information'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :address, :email, :first_name, :last_name, :phones_attributes, :phone_number
  has_many :phones, :dependent => :destroy

  accepts_nested_attributes_for :phones, :reject_if => lambda { |a| a[:phone_number].blank? }, :allow_destroy => true

  validates_presence_of :first_name, :last_name,
                        :message => ' - nemoze byt prazdne !!!'
  validates_presence_of :address,
                        :message => ' - nemoze byt prazdna !!!'
  validates_presence_of :email,
                        :message => ' - nemoze byt prazdny !!!'

  # kontrola jedinecnosti mena
  validates_uniqueness_of :last_name, :scope => :first_name,
                          :case_sensitive => false,
                          :message => ' - uzivatel s danym menom uz existuje !!!'

  #kontroluje spravnost formatu emailovej adresy
  validates_format_of :email,
                      :message => ' - nespravny format emailu !!!',
                      :allow_blank => true,
                      :with =>
                          %r{^(?:[_a-z0-9-]+)(\.[_a-z0-9-]+)*@([a-z0-9-]+)(\.[a-zA-Z0-9\-\.]+)*(\.[a-z]{2,4})$}i



end

app/models/phone.rb
class Phone < ActiveRecord::Base
  attr_accessible :contact_id, :phone_number, :phone_type, :contacts_attributes
  belongs_to :contacts

  # kontroluje spravnost mobilneho telefonneho cisla v medzinarodnom formate +421 911 123 456
  validates_format_of :phone_number,
                      :presence => true,
                      :message => ' - nespravny format - zadaj v medzinarodnom formate +123123123',
                      :with =>
                          %r{^[+]\d}i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new
    @contact.phones.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def button_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    button_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end

  def full_title(page_title)
    base_title = "Personal contacts"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
        <div id="error_explanation" xmlns="http://www.w3.org/1999/html">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  </fieldset>

  <%= f.fields_for :phones do |builder| %>
    <%= render "phone_fields", :f => builder %>
  <% end %>

  <p>
    <%= button_to_add_fields "Add number", f, :phones %>
  </p>
  <br /><br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/_phone_fields.html.erb
<div class="fields">

  <%= f.label :phone_type %>
  <%= f.select(:phone_type, [['Mobil', 'Mobil'], ['Home', 'Home'], ['Work', 'Work']]) %>
  <%= f.label :phone_number, "Phone number" %>
  <%= f.text_field :phone_number %><br />

  <%= f.hidden_field :_destroy %>

  <%= button_to_function "delete number", "remove_fields(this)" %><br /><br />

 </div>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>
<div class="CSSTableGenerator">
<table>
  <tr>
    <td>First name</td>
    <td>Last name</td>
    <td>Address</td>
    <td>Email</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.first_name %></td>
    <td><%= contact.last_name %></td>
    <td><%= contact.address %></td>
    <td><%= contact.email %></td>
    <td><%= link_to 'Show', contact_path(contact) %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Destroy', contact_path(contact), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
</div>
<br />

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>
<fieldset>
<p>
  <b>First name:</b>
  <%= @contact.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @contact.last_name %>
</p>

<p>
  <b>Address:</b>
  <%= @contact.address %>
</p>

<p>
  <b>Email:</b>
  <%= @contact.email %>
</p>
</fieldset>
<div class="CSSTableGenerator">
<table>
  <tr>
    <td>Phone type</td>
    <td>Phone number</td>
  </tr>
  <% @contact.phones.each do |phone|  %>
      <tr class="<%= cycle('line_odd', 'line_even') %>" >
        <td><%= phone.phone_type %></td>
        <td><%= phone.phone_number %></td>
      </tr>

  <% end %>
</table>
</div>
<br /><br />
<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <b>Personal contacts</b> by Martin SAMEK
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact information", contact_information_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <h4>
      <%= link_to "Personal contacts", root_path, id: "logo" %>
      </h4>
        <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'Contact') %>
<h1>About Personal Contacts</h1>

<p>
  This is a demo app which demonstrates using nested form.
  With this app you can create contacts with more phone number.
  Phone number may by different types. You can insert, edit and destroy contacts.
</p>

app/views/static_pages/contact_information.html.erb
<h1>contact information</h1>
<p>email : <b>martinsamek51@gmail.com</b></p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>This is a place for <b>HELP</b></p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Personal contacts</h1>

  <%= link_to "Come in", contacts_path  , class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("contacts.jpg") %>